apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-server-app
  namespace: mlflow
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/bibekyess/argocd-practice.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: mlflow 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
